using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ASMgenerator8080
{
    class Constants
    {
        public static List<string> Commands = new List<string>
        {
            "MOV",
            "MVI",
            "LXI",
            "LDA",
            "LHLD",
            "LDAX",
            "STA",
            "SHLD",
            "STAX",
            "PUSH",
            "POP",
            "XTHL",
            "IN",
            "OUT",
            "ADD",
            "ADI",
            "ADC",
            "ACI",
            "SUB",
            "SUI",
            "SBB",
            "SBI",
            "ANA",
            "ANI",
            "ORA",
            "ORI",
            "XRA",
            "XRI",
            "CMP",
            "CPI",
            "INR",
            "INX",
            "DCR",
            "DCX",
            "DAD",
            "RLC",
            "RRC",
            "RAL",
            "RAR",
            "CMA",
            "JMP",
            "JNZ",
            "JNC",
            "JPO",
            "JP",
            "JZ",
            "JC",
            "JPE",
            "JM",
            "CALL",
            "PCHL",
            "RNZ",
            "RNC",
            "RPO",
            "RP",
            "RZ",
            "RC",
            "RPE",
            "RM",
            "RET",
            "CNZ",
            "CNC",
            "CPO",
            "CP",
            "CZ",
            "CC",
            "CPE",
            "CM",
            "HLT",
            "NOP",
            "END"
        };
    }
}
